import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const Roxborough = localFont({
  src: [
    {
      path: "./fonts/RoxboroughCF-HeavyItalic.woff2",
      weight: "900",
      style: "italic",
    },
    {
      path: "./fonts/RoxboroughCF-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    }
  ],
  variable: "--font-roxb",
});

const HelveticaNeue = localFont({
  src: [
    {
      path: "./fonts/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNeueLightItalic.otf",
      weight: "300",
      style: "normal",
    }
  ],
  variable: "--font-helvetica",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Roxborough.variable} ${HelveticaNeue.variable} antialiased relative min-h-[600vh]`}
      >
        <div className=" absolute inset-0 bg-noise"></div>
        <div className=" absolute inset-0 bg-black/85"></div>
        {children}
      </body>
    </html>
  );
}
